name: VSQR Deployer
on: workflow_dispatch

jobs:
  build-and-publish:
    runs-on: self-hosted  # <--- This forces it to run on your Raspberry Pi
    steps:
      - name: 1. Pull Latest Code
        uses: actions/checkout@v4

      - name: 2. Install Dependencies
        run: npm install

      - name: 3. Build & Publish
        run: vsce publish -p ${{ secrets.DEPLOYMENT_KEY }}
        env:
          VSCE_PAT: ${{ secrets.DEPLOYMENT_KEY }}
